title: Michele Piazzai
description: Universidad Carlos III de Madrid
taglong: Universidad Carlos III de Madrid
tagshort: UC3M
url: https://piazzai.github.io
permalink: pretty
repo: https://github.com/piazzai/piazzai.github.io

exclude:
  - LICENSE
  - README.md

sass:
  sass_dir: _sass
  sourcemap: never