title: Michele Piazzai
description: University of Edinburgh
url: https://piazzai.github.io
author: Michele Piazzai
permalink: pretty

exclude:
  - Gemfile
  - LICENSE
  - README.md
  - docs/
  - vendor/
  - assets/fonts/
  - svg-inkscape/
  - '*.aux'
  - '*.fdb_latexmk'
  - '*.fls'
  - '*.log'
  - '*.out'
  - '*.pdf_tex'
  - '*.synctex.gz'
  - '*.xdv'
  - '*.tex'

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
